### ISSUE TITLE
视频替换工具还可以吗

### ISSUE THREAD

**Issue by katyperry13** [coldrainf/ACSpider#2]
找不到dm.coldrain.top的服务器IP地址，请问还有方法用吗

**Comment by coldrainf** [comment]
额，我改域名了，虽然还是有不少ip访问。想用的话自己写一个吧，很简单的

**Comment by katyperry13** [comment]
> 额，我改域名了，虽然还是有不少ip访问。想用的话自己写一个吧，很简单的

新的域名可以分享一下么，谢谢大佬了！

**Comment by coldrainf** [comment]
很抱歉。一朝被蛇咬十年怕井绳，之前被b站警告了，我怕传播了会出事

**Comment by cool-delete** [comment]
> 很抱歉。一朝被蛇咬十年怕井绳，之前被b站警告了，我怕传播了会出事

大哥 换源千万把啦 看重的是dm 源码里面的dm=cid后台搞不明白诶 能给出实现么
